export type ClientLogo = {
  name: string;
  src: string;
};

/** Hospitality clients shown on About — logos in /public/brand/clients/. */
export const clientLogos: ClientLogo[] = [
  { name: "88 Best Villas", src: "/brand/clients/88-best-villas.jpg" },
  { name: "AKRA Collection", src: "/brand/clients/akra-collection.png" },
  { name: "Alama Sea Village", src: "/brand/clients/alama-sea-village.jpg" },
  { name: "Alinda Villas", src: "/brand/clients/alinda-villas.jpg" },
  { name: "Andaman Breeze", src: "/brand/clients/andaman-breeze.jpg" },
  { name: "Andaman Sea Kayak", src: "/brand/clients/andaman-sea-kayak.jpg" },
  { name: "Andaman Vibes", src: "/brand/clients/andaman-vibes.jpg" },
  { name: "Ao Luek Panoramic", src: "/brand/clients/ao-luek-panoramic.jpg" },
  { name: "Asaya Kata", src: "/brand/clients/asaya-kata.jpg" },
  { name: "Baan 125 Stay", src: "/brand/clients/baan-125-stay.jpg" },
  { name: "Baan Taranya Resort", src: "/brand/clients/baan-taranya.png" },
  { name: "Blue Canyon", src: "/brand/clients/blue-canyon.jpg" },
  { name: "BYD Lofts", src: "/brand/clients/byd-lofts.png" },
  { name: "Casa de Lipe", src: "/brand/clients/casa-de-lipe.png" },
  { name: "Casa Solana Patong", src: "/brand/clients/casa-solana.webp" },
  { name: "Chestnut Hill", src: "/brand/clients/chestnut-hill.jpg" },
  { name: "Club Bamboo", src: "/brand/clients/club-bamboo.jpg" },
  { name: "Coastal Escape", src: "/brand/clients/coastal-escape.png" },
  { name: "Destination Group", src: "/brand/clients/destination-group.jpg" },
  { name: "Fantasea Plus", src: "/brand/clients/fantasea-plus.png" },
  { name: "Hawa House", src: "/brand/clients/hawa-house.jpg" },
  { name: "Holiday Inn Karon", src: "/brand/clients/holiday-inn-karon.jpg" },
  { name: "Holiday Inn Surin", src: "/brand/clients/holiday-inn-surin.png" },
  { name: "Hotel COCO Phuket", src: "/brand/clients/hotel-coco.jpg" },
  { name: "Island Escape by Burasari", src: "/brand/clients/island-escape-burasari.webp" },
  { name: "La Saine City Resort", src: "/brand/clients/la-saine-city-resort.jpg" },
  { name: "Le Kiri", src: "/brand/clients/le-kiri.jpg" },
  { name: "Le Petit", src: "/brand/clients/le-petit.png" },
  { name: "Long Beach Chalet", src: "/brand/clients/long-beach-chalet.jpg" },
  { name: "Maple Travel", src: "/brand/clients/mapple-travel.jpg" },
  { name: "Margarita Beach", src: "/brand/clients/margarita-beach.jpg" },
  { name: "ME Logo", src: "/brand/clients/me-hotel.jpg" },
  { name: "NAKA Yacht Charter", src: "/brand/clients/naka-yacht-charter.jpg" },
  { name: "Phuket Boat Quay", src: "/brand/clients/phuket-boat-quay.jpg" },
  { name: "Phunaya", src: "/brand/clients/phunaya.jpg" },
  { name: "Ramada Chaofa", src: "/brand/clients/ramada-chaofa.png" },
  { name: "Rush On", src: "/brand/clients/rush-on.jpg" },
  { name: "Sivana Villas Hua-Hin", src: "/brand/clients/sivana-hua-hin.jpg" },
  { name: "Southsea Khaolak Beach Resort", src: "/brand/clients/southsea-khaolak.jpg" },
  { name: "T-Villa Naiyang", src: "/brand/clients/t-villa-naiyang.jpg" },
  { name: "The Taksim Royal Beach Hotel", src: "/brand/clients/taksim-royal-beach.jpg" },
  { name: "The Yama Hotel Phuket", src: "/brand/clients/the-yama-hotel.jpg" },
  { name: "Timber Society", src: "/brand/clients/timber-society.jpg" },
  { name: "Union Voyage", src: "/brand/clients/union-voyage.jpg" },
  { name: "Universe Supply", src: "/brand/clients/universe-supply.jpg" },
  { name: "Wonder Valley", src: "/brand/clients/wonder-valley.jpg" },
  { name: "Wyndham Grand Nai Harn", src: "/brand/clients/wyndham-grand-nai-harn.jpg" },
];
